# Generated by Django 3.0.5 on 2020-04-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTELY', 'Quartely'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=8)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personalfinance.Tags')),
            ],
        ),
    ]
